Update main.tf
Added IAM roles and policy attachments for each lambda function. Added more locals and changed where they needed to be used. Terraform plan runs fine, however terraform apply fails with this error:

Error: creating IAM Role (iam-for-lambda-get): InvalidClientTokenId: The security token included in the request is invalid
│ 	status code: 403, request id: 1af89868-eeed-4fff-a2b9-6b5ae4fb7a14

as well as an error for the IAM policy:

Error: creating IAM Policy lambda-logging-functions: InvalidClientTokenId: The security token included in the request is invalid
│ 	status code: 403, request id: 8eec7f37-badc-4d6f-b25b-21bf880e07a5


Tried creating IAM policies for each function caused more errors. They are commented out so there is only 1 general IAM policy.